name: mfakto CD

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  Linux:
    name: Linux
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]
      fail-fast: false
    steps:
    - uses: actions/checkout@v7

    - name: Build
      run: |
        docker run --rm -i -v "$GITHUB_WORKSPACE:/workspace" -w /workspace centos:7 bash -s -e -o pipefail <<'EOF'
        sed -i '/^mirrorlist/d;/^#baseurl=/{s|^#||;s|/mirror|/vault|;}' /etc/yum.repos.d/CentOS*.repo
        # yum update -y
        yum install -y centos-release-scl epel-release
        if [[ $HOSTTYPE == aarch64 ]]; then repo=altarch; else repo=centos; fi
        sed -i "s|/centos/7/|/$repo/7/|g;/^mirrorlist/d;/^# *baseurl=/{s|^# *||;s|/mirror|/vault|;}" /etc/yum.repos.d/CentOS-SCLo-*.repo
        yum install -y devtoolset-10-gcc-c++ devtoolset-10-libstdc++-static make ocl-icd-devel

        source /opt/rh/devtoolset-10/enable
        gcc --version
        ldd --version

        make -C src -j "$(nproc)"
        EOF

    - name: Upload build artifacts
      uses: actions/upload-artifact@v7
      with:
        name: mfakto-linux-${{ endsWith(matrix.os, '-arm') && 'ARM64' || 'x64' }}
        path: |
          *.cl
          Changelog-mfakto.txt
          COPYING
          datatypes.h
          mfakto
          mfakto.ini
          README-SpecialVersions.txt
          README.txt
          tf_debug.h
          todo.txt

    - name: Create artifacts and release assets
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        tar -cvjf mfakto-linux-${{ endsWith(matrix.os, '-arm') && 'ARM64' || 'x64' }}.tar.bz2 *.cl Changelog-mfakto.txt COPYING datatypes.h mfakto mfakto.ini README-SpecialVersions.txt README.txt tf_debug.h todo.txt
    - name: Release
      uses: softprops/action-gh-release@v3
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          mfakto-linux-${{ endsWith(matrix.os, '-arm') && 'ARM64' || 'x64' }}.tar.bz2

  WindowsMSVC:
    name: Windows MSVC
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022, windows-11-arm]
      fail-fast: false
    steps:
    - uses: actions/checkout@v7
    - uses: step-security/msvc-dev-cmd@v1
      with:
        arch: ${{ endsWith(matrix.os, '-arm') && 'amd64_arm64' || 'x64' }}

    - name: Install dependencies
      run: |
        vcpkg integrate install --vcpkg-root=c:\vcpkg

    - name: Build
      run: |
        msbuild mfaktoVS12.vcxproj /p:Configuration=Release /p:Platform=${{ endsWith(matrix.os, '-arm') && 'ARM64' || 'x64' }}

    - name: Create artifacts and release assets
      run: |
        Copy-Item -Path Changelog-mfakto.txt, COPYING, README-SpecialVersions.txt, README.txt, todo.txt -Destination ${{ endsWith(matrix.os, '-arm') && 'ARM64' || 'x64' }}/Release/
        Compress-Archive -DestinationPath mfakto-windows-${{ endsWith(matrix.os, '-arm') && 'ARM64' || 'x64' }}.zip -CompressionLevel Optimal -Path ${{ endsWith(matrix.os, '-arm') && 'ARM64' || 'x64' }}/Release/*

    - name: Upload build artifacts
      uses: actions/upload-artifact@v7
      with:
        name: mfakto-windows-${{ endsWith(matrix.os, '-arm') && 'ARM64' || 'x64' }}
        path: ${{ endsWith(matrix.os, '-arm') && 'ARM64' || 'x64' }}/Release/

    - name: Release
      uses: softprops/action-gh-release@v3
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
           mfakto-windows-${{ endsWith(matrix.os, '-arm') && 'ARM64' || 'x64' }}.zip

  macOS:
    name: macOS
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-15, macos-15-intel]
      fail-fast: false
    env:
      # Used by CI workflow file. For mapping from "runs-on" / "os" to architecture, see:
      # https://docs.github.com/en/actions/how-tos/write-workflows/choose-where-workflows-run/choose-the-runner-for-a-job#standard-github-hosted-runners-for-public-repositories
      SELFARCH: ${{ endsWith(matrix.os, '-intel') && 'x64' || 'ARM64' }}
      # Just because we use a new builder doesn't mean we don't want the build to run on an older OS
      MACOSX_DEPLOYMENT_TARGET: 10.13
    steps:
    - uses: actions/checkout@v7

    - name: Build
      run: |
        make -C src -j "$(sysctl -n hw.ncpu)"

    - name: Upload build artifacts
      uses: actions/upload-artifact@v7
      with:
        name: mfakto-macos-${{ env.SELFARCH }}
        path: |
          *.cl
          Changelog-mfakto.txt
          COPYING
          datatypes.h
          mfakto
          mfakto.ini
          README-SpecialVersions.txt
          README.txt
          tf_debug.h
          todo.txt

    - name: Create artifacts and release assets
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        tar -cvjf mfakto-macos-${{ env.SELFARCH }}.tar.bz2 *.cl Changelog-mfakto.txt COPYING datatypes.h mfakto mfakto.ini README-SpecialVersions.txt README.txt tf_debug.h todo.txt

    - name: Release
      uses: softprops/action-gh-release@v3
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          mfakto-macos-${{ env.SELFARCH }}.tar.bz2
